//! Embed `assets/models/*.png`, sharing one copy of identical bytes so
//! placeholder duplicates do not bloat the binary.

use std::collections::BTreeMap;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=assets/models");

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let models_dir = manifest.join("assets/models");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("model_images.rs");

    let placeholder_src = models_dir.join("placeholder.png");
    let placeholder_bytes = fs::read(&placeholder_src).unwrap_or_default();
    fs::write(out_dir.join("placeholder.png"), &placeholder_bytes)
        .expect("write placeholder.png to OUT_DIR");

    let mut hash_to_file: BTreeMap<u64, String> = BTreeMap::new();
    let mut id_to_hash: BTreeMap<String, u64> = BTreeMap::new();

    if models_dir.is_dir() {
        let mut entries: Vec<fs::DirEntry> = fs::read_dir(&models_dir)
            .expect("read assets/models")
            .filter_map(|e| e.ok())
            .collect();
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()).map(|e| e.eq_ignore_ascii_case("png"))
                != Some(true)
            {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("")
                .to_ascii_lowercase();
            if stem.is_empty() || stem == "placeholder" {
                continue;
            }
            let Ok(bytes) = fs::read(&path) else {
                continue;
            };
            let hash = file_hash(&bytes);
            hash_to_file.entry(hash).or_insert_with(|| {
                let name = format!("{hash:016x}.png");
                fs::write(out_dir.join(&name), &bytes).expect("write unique model png");
                name
            });
            id_to_hash.insert(stem, hash);
        }
    }

    let mut src = String::from(
        r#"// @generated by build.rs — do not edit.
pub const PLACEHOLDER_PNG: &[u8] = include_bytes!("placeholder.png");

"#,
    );

    let mut const_names: BTreeMap<u64, String> = BTreeMap::new();
    for (i, (hash, file)) in hash_to_file.iter().enumerate() {
        let name = format!("IMG_{i}");
        src.push_str(&format!(
            "const {name}: &[u8] = include_bytes!(\"{file}\");\n"
        ));
        const_names.insert(*hash, name);
    }

    src.push_str(
        r#"
pub fn model_png(id: &str) -> &'static [u8] {
    match id {
"#,
    );
    for (id, hash) in &id_to_hash {
        let cname = const_names.get(hash).expect("hash const");
        src.push_str(&format!("        \"{id}\" => {cname},\n"));
    }
    src.push_str(
        r#"        _ => PLACEHOLDER_PNG,
    }
}
"#,
    );

    fs::write(&dest, src).unwrap_or_else(|err| {
        panic!("could not write {}: {err}", dest.display());
    });
}

fn file_hash(bytes: &[u8]) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    bytes.hash(&mut hasher);
    hasher.finish()
}
